### ISSUE TITLE
Disappearing entity Bug

### ISSUE THREAD

**Issue by ArikVhedrovix** [Deep-Phield-Softworks/XeroSum#21]
After being told to move several times, the entity disappears. If you attempt to right click to move
after entity disappears you get a crash:

Traceback (most recent call last):
  File "main.py", line 156, in <module>
    mainLoop()
  File "main.py", line 24, in mainLoop
    mouseClick(event)
  File "main.py", line 64, in mouseClick
    mouseRightClick(event)
  File "main.py", line 94, in mouseRightClick
    p = Path(goalKeys, SELECTED, playerView)
  File "D:\@Dev\@Git\@XeroSum\XeroSum\Path.py", line 27, in __init__
    self.createFacings()
  File "D:\@Dev\@Git\@XeroSum\XeroSum\Path.py", line 73, in createFacings
    self.facings.append(self.facings[-1])
IndexError: list index out of range

**Comment by ArikVhedrovix** [comment]
Possible relation to [Bug #35] (https://github.com/Deep-Phield-Softworks/XeroSum/issues/35)

**Comment by ArikVhedrovix** [comment]
Closing for now after ZODB integration. Will reopen if behaviour is manifest again.
