### ISSUE TITLE
Mac startup bug

### ISSUE THREAD

**Issue by CToups** [Deep-Phield-Softworks/XeroSum#58]
In the first occurrence of a truly random startup error I've ever seen, the game fails to start an average of about 4 out of 5 times. The error message is:

Christophers-MacBook-Pro:XeroSum CT$ python2.7-32 main.py
ACTIVE CHUNKS #: 4
ACTIVE CHUNK IDS: ['-1_-1_0', '-1_0_0', '0_-1_0', '0_0_0']
Traceback (most recent call last):
  File "main.py", line 225, in <module>
    main_loop()
  File "main.py", line 57, in main_loop
    playRandomSong() #Play a random song
  File "main.py", line 164, in playRandomSong
    pygame.mixer.music.load(str(tracks[n]))
pygame.error: Module format not recognized

For reference, when the game does start up, the following is printed to terminal:

Christophers-MacBook-Pro:XeroSum CT$ python2.7-32 main.py
ACTIVE CHUNKS #: 4
ACTIVE CHUNK IDS: ['-1_-1_0', '-1_0_0', '0_-1_0', '0_0_0']

**Comment by CToups** [comment]
Though the exact cause of the bug remains unknown, wrapping the code cited in the error report in a try : catch loop fixed the bug. Perhaps this is something that will have to be revisited, or perhaps this is just one of the many things out there that just plain have to be in a try catch. Either way, for now, fixed.
